on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/hello')

    steps:
      - uses: LightningStairs/comment_action@v4
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
